### ISSUE TITLE
How are the ear masks generated ?

### ISSUE THREAD

**Issue by sahilsid** [sicxu/Deep3dPortrait#11]
The roi-tanh warping model for face segmentation trained on the helen dataset does not give the segmenation for the ear region. How is this achieved ?

**Comment by sicxu** [comment]
We just use the roi-tanh warping method training on a dataset with annotations for ears.

**Comment by sahilsid** [comment]
@sicxu  Could you tell me what is the dataset that you used for training roi-tanh ?

**Comment by sicxu** [comment]
CelebA-HQ

**Comment by brunovollmer** [comment]
Is the training code for the roi-tanh method published somewhere?

**Comment by sicxu** [comment]
Sorry for the inconvenience, there is no offical implementation of roi-tanh method, @cravisjan97 mentioned an implementation here https://github.com/sicxu/Deep3dPortrait/issues/6#issue-643412892. For more details about the method, please refer to Lin et al. 's paper.
