### ISSUE TITLE
expression Manipulation

### ISSUE THREAD

**Issue by WangYanru-NJU** [sicxu/Deep3dPortrait#12]
Thank you for this work!   
What is the current expression Manipulation pipline？Should I change the exp params then render the new face depth map? But this new depth map is not consistent  with the input image which is in the orgin expression when I take them as the input of depthnet, it doesn't matter ?

**Comment by Turlan** [comment]
The expression manipulation is based on the reconstructed head geometry.  We didn't render new face depth as the input to the depth net.

**Comment by sicxu** [comment]
The expression manipulation is based on the reconstructed head geometry.  We didn't render new face depth as the input to the depth net.

**Comment by jolt2017** [comment]
Thanks for you work. In your paper, you talk little about how to manipulating head pose. Would you like to introduce this part by more words

**Comment by sicxu** [comment]
pseudo code:
```python
# xyz: BxNx3
xyz = xyz - src_trans
xyz = np.einsum('aij,ajk->aik', xyz, src_rotation)
xyz = np.einsum('aij,ajk->aik', xyz, tgt_rotation.T))
xyz = xyz + src_trans
```
