### ISSUE TITLE
What's the mean of the depth?

### ISSUE THREAD

**Issue by tjusxh** [sicxu/Deep3dPortrait#19]
Thanks for your good work. I read your release code. We can get the depth map of face and head by render_sess in step1_recon_3d_face and step3_get_head_geometry. The values of the depth map from 8 to 10.2 . What's the physical mean of the depth values? Where is the zero of the depth？ Thank you very much.

**Comment by sicxu** [comment]
We predefine the carmera distance as 10 decimeter(dm). Given a 3d point defined as (x, y, z), the depth equals 10 - z.
