### ISSUE TITLE
render face disalignment with the input face

### ISSUE THREAD

**Issue by miaoYuanyuan** [sicxu/Deep3dPortrait#24]
Hi, Thank you for this work. when I use the Render_block referenced the 'Deep3DFaceReconstruction'  render the recon_face and paste on the origial image face. the render face cannot overlay the original face correctly, alway with scale and offset disalignment.  the focal  use 1015 as default as your code , and the camare position also default.   can you give me some suggestion? Thank you !

**Comment by sicxu** [comment]
To be clear, is your question related to Deep3DFaceReconstruction's results? If so:
In Deep3DFaceReconstruction, the recon_face is based on the input cropped image. Have you  ever tried to directly align the recon_face to the input? If this part is correct, you may check your calculation of the inverse of [transform_params](https://github.com/microsoft/Deep3DFaceReconstruction/blob/05d0786aea5aa267103040d9a91b3a3a23dd58de/demo.py#L71).  If possible, could you  provide your input  and result for more info?

**Comment by miaoYuanyuan** [comment]
Thank you ! I got the correct render result.
