### ISSUE TITLE
rasterize_triangles_kernel_1.so not found

### ISSUE THREAD

**Issue by huang1030** [sicxu/Deep3dPortrait#26]
Thank you for your code.When I run python step1_recon_3d_face. The following errors in py 

tensorflow. Python. Framework. Errors_impl. NotFoundError: Deep3dPortrait\utils\render\rasterize_triangles_kernel_1.so not found

I use Windows, not Linux. Is this question related to the system? I am looking forward to your reply. Thanks.

**Comment by sicxu** [comment]
Yes, currently we use the tf_mesh_renderer for image rendering, which can only be used on Linux.
