### ISSUE TITLE
About tf_mesh_render

### ISSUE THREAD

**Issue by taylorlu** [sicxu/Deep3dPortrait#3]
Hi, what's the difference between you code and google's tf_mesh_render?
There's only compiled library but I cannot find the c++ code, any plan to share the source code?
Thanks in advance.

**Comment by sicxu** [comment]
Differences: Please refer to lines 223~228 in utils/mesh_renderer.py and lines 52~57 in utils/rasterize_triangles.py  for details.
Source code: We didn't modifiy the c++ code. For full source code, please refer to https://github.com/google/tf_mesh_renderer/tree/ba27ea1798f6ee8d03ddbc52f42ab4241f9328bb
