### ISSUE TITLE
Issue with rasterize_triangles_kernel.so

### ISSUE THREAD

**Issue by cravisjan97** [sicxu/Deep3dPortrait#4]
I have installed the tensorflow-gpu=1.12 using conda. When I run the code ```python step1_recon_3d_face.py```, I get the following error:

```
rasterize_triangles_kernel_1.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs
```

How do I solve this error?

**Comment by sahilsid** [comment]
@cravisjan97 Hi ! were you able to solve the error ?

**Comment by cravisjan97** [comment]
Yes. Was able to solve it. This was due to an incompatibility issue with Tensorflow version

**Comment by sahilsid** [comment]
@cravisjan97 Could you explain how you solved the issue ? Which tensorflow version did you use ?

**Comment by cravisjan97** [comment]
I used the Tensorflow-gpu==1.12.0 version. But I observed that I got the same error when I installed tensorflow using conda. An alternative to this would be to create a conda environment and pip install tensorflow-gpu (not conda install). You can then install cudatoolkit using conda. This solved the issue. I don't know why conda install tensorflow-gpu==1.12.0 throws this error. Hope this helps!
