### ISSUE TITLE
How to generate face segmented masks with the same size as input image?

### ISSUE THREAD

**Issue by cravisjan97** [sicxu/Deep3dPortrait#7]
I noticed that the masks in your ./example/ folder have the same size as the input image which varies. Most of the face segmentation approached resize their input image and hence generate masks which are of fixed size. But the masks in your example/ folder have varying size. How did you achieve this? This would be really helpful to me as I would like to test your model on an arbitrary image.

**Comment by Suvi-dha** [comment]
Just use this code `https://github.com/LeoGitGuy/PSFRGAN/blob/master/test_enhance_single_unalign.py` for face segmentation. If you want the output mat file same size as of input image, Switch off the "detect and align" function before "enhance_faces" function and use original image as input to this function. You may just need the parse maps,  comment the high quality model.
