### ISSUE TITLE
rasterize_triangles_kernel_1.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs

### ISSUE THREAD

**Issue by sahilsid** [sicxu/Deep3dPortrait#8]
Error in compiled renderer. Says : rasterize_triangles_kernel_1.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs
Running : 
              Ubuntu 16.04
              Tensorflow-gpu 1.12.0
              CUDA 9.0

**Comment by sicxu** [comment]
Hi, this is very strange, since I have test the .so file in the environment. This error may occur when the tf version  does not match the .so file. However, based on the information you provided, it seems the tf version you are using is right. Maybe you can wait for #4 's reply.
