### ISSUE TITLE
Landmark detection

### ISSUE THREAD

**Issue by cravisjan97** [sicxu/Deep3dPortrait#9]
I am currently using the https://github.com/1adrianb/face-alignment for 2D landmark detection. I am running the following code snippet:

```
import face_alignment
fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D, flip_input=False)
img = cv2.imread('./examples/1_1234.jpg')
preds = fa.get_landmarks(img)[0] # (68,2)
``` 
But the 2D landmark points I get are very different from the ones in the ./examples/1_1234_landmark.txt. Am I using the right landmark package for this model?

Thanks in advance

**Comment by sicxu** [comment]
Hi, could you provide more details about the differences ?

**Comment by cravisjan97** [comment]
@sicxu Thank you for the reply!!!

The difference is as follows:

- If I use the above code snippet, I get the landmarks as follows (for ./examples/1_1234.jpg): [265, 405, 265, 470, ... , 608, 427, 608]

- The landmark given in ./examples/1_1234_landmark.txt is as follows: [286.377, 710.610, 288.955, 654.239, ... ,512.079, 429.0005, 514.309]

![snapshot00](https://user-images.githubusercontent.com/11577265/86137673-63cbf280-baa2-11ea-92c3-818a71c86e5c.png)

The above snapshot is obtained using your example mask(./examples/1_1234.mat) and example landmark(./examples/1_1234_landmark.txt) files

![snapshot00](https://user-images.githubusercontent.com/11577265/86137847-94ac2780-baa2-11ea-9bc3-ab0974ea557e.png)

The above snapshot is obtained using your example mask ('./examples/1_1234.mat) and the landmark detection generated from the above code snippet.

There is a clear change in the quality of the 3D models generated.

**Comment by sicxu** [comment]
Sorry for the missing description, the provided landmarks in ./examples are defined in 3D sapce coordinates (X-Y plane). You can apply the following tranform to Bulat et al.'s results. Also, the landmarks should be 3D definition for better performance.
https://github.com/sicxu/Deep3dPortrait/blob/fad83d78cea303eb3da24afd59fac960eb3f6f38/utils/preprocess.py#L150

![image](https://user-images.githubusercontent.com/64250193/86142885-4e98a780-bb26-11ea-9714-b0826dd2b28d.png)
**The differece between two kinds of coordinates.**  Red points: draw the landmark in ./examples directly onto image plane; Blue points: after apply the transform.

**Comment by cravisjan97** [comment]
Thanks a lot @sicxu. Now it works!!!

**Comment by HulkMaker** [comment]
> Thanks a lot @sicxu. Now it works!!!

hi cravisjan，

Glad to see you have figure this issue out.
I am using the same face-alignment project, and also met this issue now. After reading this ticket, I am not very clear how you figure this issue out., could you provide more detial?
1. which function in preprocess.py file you finally use, facerecon_preprocess_yu_5p or facerecon_preprocess ?
2. In face landmark detection step, you use "fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D)" or "fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._3D)"？

Look forward to your response!

**Comment by jly0810** [comment]
> 非常感谢@sicxu。现在它起作用了！！！

I want to use my photos to generate a 3D portrait model.I have generated the landmark.txt file according to your method .And I'd like to ask you how to generate the detection.txt files and the .mat file？
